### ISSUE TITLE
退出登录后没有清除vuex内的路由数据

### ISSUE THREAD

**Issue by zmjm** [zouzhibin/vue-admin-perfect#1]
退出登录后，页面不刷新直接登录，由于没清楚store内的路由数据，面包屑导航会显示登录的导航块

**Comment by zouzhibin** [comment]
> 退出登录后，页面不刷新直接登录，由于没清楚store内的路由数据，面包屑导航会显示登录的导航块

感谢你的建议，已经修复

**Comment by overdose0519** [comment]
装下eslint吧，代码规范还是挺重要的 代码拉下来之后 vscode一堆红点警告

**Comment by zouzhibin** [comment]
已关闭
