### ISSUE TITLE
总体上很好，提两个小建议

### ISSUE THREAD

**Issue by ccpwcn** [zouzhibin/vue-admin-perfect#2]
- 表格数据，或者其他一些数据量相对较大的组件加载数据的时候，最好要有loading，这样交互会好很多💯
- 登录页有点丑，这是脸面，最好优化一下，毕竟现在是个看脸的时代、😂

**Comment by zouzhibin** [comment]
> * 表格数据，或者其他一些数据量相对较大的组件加载数据的时候，最好要有loading，这样交互会好很多💯
> * 登录页有点丑，这是脸面，最好优化一下，毕竟现在是个看脸的时代、😂
感谢你提的建议，我也想变得好看呀，没有UI设计

**Comment by zouzhibin** [comment]
> > * 表格数据，或者其他一些数据量相对较大的组件加载数据的时候，最好要有loading，这样交互会好很多💯
> > * 登录页有点丑，这是脸面，最好优化一下，毕竟现在是个看脸的时代、😂
> >   感谢你提的建议，我也想变得好看呀，没有UI设计

**Comment by ccpwcn** [comment]
> 



> > > * 表格数据，或者其他一些数据量相对较大的组件加载数据的时候，最好要有loading，这样交互会好很多💯
> > > * 登录页有点丑，这是脸面，最好优化一下，毕竟现在是个看脸的时代、😂
> > >   感谢你提的建议，我也想变得好看呀，没有UI设计

可以去找一个做的漂亮的抄一下，天下代码一大抄啊。哈哈。。。
