### ISSUE TITLE
标签页功能

### ISSUE THREAD

**Issue by pangonglong** [zouzhibin/vue-admin-perfect#3]
想问下关于标签页的两个功能是否支持：
1.右侧内容页如何新增一个标签页
2.多页签：应用场景：不同query参数的详情页面在不同tab展示

**Comment by zouzhibin** [comment]
> 应用场景：不同query参数的详情页面在不同tab展
暂时不支持哈 ，后面会支持。。。

**Comment by Xyn19961118** [comment]
> > 应用场景：不同query参数的详情页面在不同tab展
> > 暂时不支持哈 ，后面会支持。。。

这个现在有支持了吗
