### ISSUE TITLE
大佬 我发现一个bug 在开启 Tags-Views后 刷新或关闭tabg页面 控制台会报错

### ISSUE THREAD

**Issue by cn-kelon** [zouzhibin/vue-admin-perfect#4]

**Comment by zouzhibin** [comment]
> _No description provided._

你好，感谢你提出的问题，我打开示例地址 刷新关闭并没有报错啊，有什么详细的示例步骤嘛

**Comment by cn-kelon** [comment]
好的  是 vue-admin-perfect-uniapp 这个项目下面这个分支  还有 https://ext.dcloud.net.cn/plugin?id=8271  这两个发现有这个问题

**Comment by cn-kelon** [comment]
![image](https://user-images.githubusercontent.com/46063184/178961554-b50b2bea-7d41-4f1f-86c0-3c95f1969290.png)
![image](https://user-images.githubusercontent.com/46063184/178961665-8a41ac5e-7144-411d-94fb-48d6f61206f9.png)

**Comment by cn-kelon** [comment]
期望大佬修复

**Comment by zouzhibin** [comment]
你是需要用这个版本吗

**Comment by zouzhibin** [comment]
> 你是需要用这个版本吗

其实这个版本做得比较粗糙

**Comment by cn-kelon** [comment]
我正用于生产...

**Comment by cn-kelon** [comment]
其实 除了上诉问题 然后个别uniapp组件样式冲突外 也没有发现其他问题 还是挺好用的

**Comment by zouzhibin** [comment]
> 其实 除了上诉问题 然后个别uniapp组件样式冲突外 暂时还没有发现其他问题 还是挺好用的

已经修复 ，uniapp插件市场和github都已经更新 ，只需要判断cache是否存在 
![image](https://user-images.githubusercontent.com/33242526/183060521-e7a75986-bdcf-409c-9a34-53b21f979b89.png)

**Comment by zouzhibin** [comment]
> > 其实 除了上诉问题 然后个别uniapp组件样式冲突外 暂时还没有发现其他问题 还是挺好用的
> 
> 已经修复 ，uniapp插件市场和github都已经更新 ，只需要判断cache是否存在 ![image](https://user-images.githubusercontent.com/33242526/183060521-e7a75986-bdcf-409c-9a34-53b21f979b89.png)

你可以在关闭的时候 都加个判断就行了

**Comment by cn-kelon** [comment]
好 谢谢你
